# Generated by Django 5.2.3 on 2025-06-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('position', models.CharField(choices=[('brand_protection_analyst', 'Brand Protection Analyst'), ('counterfeit_investigation_specialist', 'Counterfeit Investigation Specialist'), ('cybersecurity_specialist', 'Cybersecurity Specialist'), ('client_relations_manager', 'Client Relations Manager'), ('research_development_associate', 'Research & Development Associate'), ('marketing_communications_specialist', 'Marketing & Communications Specialist'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(blank=True, choices=[('on_site', 'On-site (Specify location later)'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20, null=True)),
                ('experience_years', models.CharField(choices=[('0_1', '0-1 years'), ('2_4', '2-4 years'), ('5_plus', '5+ years')], max_length=10)),
                ('skills', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('start_date', models.DateField()),
                ('work_schedule', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract_freelance', 'Contract / Freelance')], max_length=20, null=True)),
                ('why_join', models.TextField()),
                ('unique_skills', models.TextField(blank=True, null=True)),
                ('data_consent', models.BooleanField()),
                ('terms_agree', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
