# Generated by Django 5.2.3 on 2025-06-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('partnership_type', models.CharField(choices=[('techProvider', 'Tech Provider'), ('brandOwner', 'Brand Owner'), ('enforcementAgency', 'Enforcement Agency'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='partner_attachments/')),
                ('consent', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
