# Generated by Django 5.2.3 on 2025-06-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Partnership Opportunity', 'Partnership Opportunity'), ('Request a Demo', 'Request a Demo'), ('Report a Counterfeit Product', 'Report a Counterfeit Product'), ('Request Support', 'Request Support'), ('Media / Press Inquiry', 'Media / Press Inquiry'), ('Other', 'Other')], max_length=50)),
                ('contact_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10, null=True)),
                ('contact_time', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20, null=True)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contact_attachments/')),
                ('country', models.CharField(blank=True, choices=[('USA', 'USA'), ('UK', 'UK'), ('Kenya', 'Kenya'), ('India', 'India'), ('Germany', 'Germany'), ('Other', 'Other')], max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
