# Generated by Django 5.2.3 on 2025-06-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_invitetoken'),
    ]

    operations = [
    ]
