# Generated by Django 5.2.3 on 2025-06-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('appreciation', 'Appreciation'), ('complaint', 'Complaint'), ('counterfeit', 'Report a Counterfeit Product'), ('suggestion', 'Suggestion'), ('technical', 'Technical Issue')], max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback_attachments/')),
                ('privacy_consent', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
